In [1]:
import pandas as pd
import re 
import altair as alt

In [14]:
df=pd.read_csv('GSAF5.csv')

/Users/anurag/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3269: DtypeWarning: Columns (0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [15]:
df=df[['Date',
 'Year',
 'Type',
 'Country',
 'State',
 'Location',
 'Activity',
 'Name',
 'Sex',
 'Age',
 'Injury',
 'Fatal Y/N',
 'Time',
 'Species ']]

In [16]:
df=df[:7017]
df=df.drop_duplicates()
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species
0,29-May-25,2025.0,Unprovoked,USA,North Carolina,Sunset Beach,Swimming,Sean Barton,M,26,Gash to lower left leg,N,1100hrs,Not stated
1,15-May-25,2025.0,Unprovoked,Australia,South Australia,Port Noarlunga,Swimming,Richard Vinall,M,66,Injury to thigh,N,0945hrs,Not stated
2,08-May-25,2025.0,Unprovoked,Jamaica,Montego Bay,Rose Hall beach,Paddling,Rachel Smith,F,26,minor injuries to fingers of left hand,N,Not stated,Small shark 1m (3ft) long
3,21-Apr-25,2025.0,Unprovoked,Israel,Hadera,Olga Beach near Hadera Stream,Diving,Barak Tzach,M,45,Remains recovered several days after the attcks,Y,1500hrs,Dusky sharks
4,20-Apr-25,2025.0,Questionable,Mexico,Quntana Roo,Chac Mool Beach Cancun,Rescuing female companion,Alejandro Cortes,M,20,Victim drown and was scavenged by sharks,Y,Not stated,Not Staed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7012,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN
7013,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN
7014,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN
7015,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN
7016,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN

In [17]:
def activity_Cleaner(row):   
    swimming_pat = re.findall('[sj][wu][im][pm][m]?\w*',row['Activity'])
    #walk = /Wading /  Walking / 
    walking_pat = re.findall('[w][a][dl][k]?\w*',row['Activity'])
    #Surfing = surfing  or boogie boarding /surfng / body surfing
    surfing_pat = re.findall('[sb][ou][ador][rygf][ndi][e]?\w*',row['Activity'])
    #sailing = boating /canoeing / sailing /raft / floating/kayak
    sailing_pat = re.findall('[bcsrkf][aol][anifyo][atol][teki]?\w*',row['Activity'])
    #ep_boats = ship/yacht/adrift  (engined powered)
    ep_boats_pat =  re.findall('[sya][hda][irc][pih][ft]?\w*',row['Activity'])
    #Kite/kiting = kitesurfing/ kite boarding/ Skimboarding
    kite_pat =  re.findall('[sk][ik][it][mie][n]?\w*',row['Activity'])
    #fishing = Spearfishing / fishing /net
    fish_pat = re.findall('[fn][ie][st][h]?\w*',row['Activity'])
    #jet/skiing =  jetskiing /skiing / water-skiing
    jet_pat = re.findall('[s][k][i][i][n]\w*',row['Activity'])
    #dive = scuba diving / scuba / dive / Snorkeling
    dive_pat = re.findall('[ds][inc][vuo][eibr][ak]?\w*',row['Activity'])
    #feeding sharks =  feeding sharks
    feed_pat = re.findall('[f][e][e][d]\w*',row['Activity'])
    #taking photos = photos / photo shooting/ filming
    photo_pat = re.findall('[fp][ih][lo][tm][o]?\w*',row['Activity'])
    #bathing  = bath/bathing 
    bath_pat = re.findall('[b][a][t][h]\w*',row['Activity'])
    #floating in water :
    float_pat = re.findall('[fr][le][os][at]?\w*',row['Activity'])
    ## reading  where it will store each time the word appears in each row, if its different,
    ##it changes the value of the row 
    ## to what the 'return' has been set.
    
    if len(swimming_pat) !=0:
        return 'swimming'
    
    elif len(float_pat) !=0:
        return 'floating'
    elif len(walking_pat) !=0:
        return 'walking'
        
    elif len(bath_pat) !=0:
        return 'bathing'   
    
    elif len(surfing_pat) !=0:
        return 'surfing'
    
    elif len(sailing_pat) !=0:
        return 'sailing'
    
    elif len(ep_boats_pat) !=0:
        return 'boating'
    
    elif len(kite_pat) !=0:
        return 'kite surfing'
    
    elif len(fish_pat) !=0:
        return 'fishing'
    
    elif len(jet_pat) !=0:
        return 'skiing'
    
    elif len(dive_pat) !=0:
        return 'diving'
    
    elif len(feed_pat) !=0:
        return 'feeding'
    
    elif len(photo_pat) !=0:
        return 'Photography'
    
    else:
        return  'other'

In [18]:
df['Activity'] = df['Activity'].astype(str).str.lower()
df['Activity'] = df['Activity'].str.strip()
df['Activity'].dropna(inplace = True)

In [19]:
df['Activity'] = df.apply(activity_Cleaner, axis = 1)
df['Activity'].value_counts()

surfing         1601
swimming        1300
fishing         1259
other           1178
diving           694
sailing          287
walking          248
bathing          194
floating         107
boating           74
kite surfing      49
feeding           15
Photography        9
Name: Activity, dtype: int64

In [25]:

df_filtered = df[df['Activity'].str.lower() != 'other']

# Aggregate data
activity_counts = (
    df_filtered.groupby('Activity')
    .agg(
        Total_Attacks=('Activity', 'count'),
        Fatalities=('Fatal Y/N', lambda x: (x == 'Y').sum())
    )
    .reset_index()
    .sort_values('Total_Attacks', ascending=False)
    .head(10)
)

# Create chart
chart=alt.Chart(activity_counts).mark_bar().encode(
    x=alt.X('Total_Attacks:Q', title='Number of Attacks'),
    y=alt.Y('Activity:N', sort='-x', title='Activity'),
    color=alt.Color('Fatalities:Q', scale=alt.Scale(scheme='reds'), title='Fatalities'),
    tooltip=[
        alt.Tooltip('Activity:N', title='Activity'),
        alt.Tooltip('Total_Attacks:Q', title='Total Attacks'),
        alt.Tooltip('Fatalities:Q', title='Fatalities')
    ]
).properties(
    title='Top 10 Activities in Shark Attacks',
    width=600
)
chart

alt.Chart(...)

In [26]:
chart.save('shark_attacks_chart.html')